# -*- coding: utf-8 -*-
"""Mall.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XCPtmlW9ti_sxYgTU7OUkoxHI2ospCFz
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
 
#Cargamos el DataSet Mall_Customers.csv
 
from google.colab import files
files.upload()

dataset = pd.read_csv('Mall_Customers.csv')
X = dataset.iloc[:,[3,4]].values

from sklearn.cluster import KMeans

#Aplicamos KMeans para el dataset con un numero de 5 clusters

kmeans=KMeans(n_clusters= 5, init = 'k-means++', max_iter = 300, n_init = 10, random_state = 0)
Y_Kmeans = kmeans.fit_predict(X)

# Visualizamos el grafico

plt.scatter(X[Y_Kmeans == 0, 0], X[Y_Kmeans == 0,1],s = 100, c='red', label = 'Cluster 1')

plt.scatter(X[Y_Kmeans == 1, 0], X[Y_Kmeans == 1,1],s = 100, c='blue', label = 'Cluster 2')

plt.scatter(X[Y_Kmeans == 2, 0], X[Y_Kmeans == 2,1],s = 100, c='green', label = 'Cluster 3')

plt.scatter(X[Y_Kmeans == 3, 0], X[Y_Kmeans == 3,1],s = 100, c='cyan', label = 'Cluster 4')

plt.scatter(X[Y_Kmeans == 4, 0], X[Y_Kmeans == 4,1],s = 100, c='magenta', label = 'Cluster 5')

plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], s = 300, c = 'yellow', label = 'Centroids')
    
plt.title('Clusters de clientes')
plt.xlabel('INGRESO ANUAL (k$)')
plt.ylabel('PORCENTAJE DE GASTO (1-100)')
plt.legend()
plt.show()

Y = dataset.iloc[:,[2,4]].values

from sklearn.cluster import KMeans

#Aplicamos KMeans para el dataset con un numero de 5 clusters

kmeans=KMeans(n_clusters= 5, init = 'k-means++', max_iter = 300, n_init = 10, random_state = 0)
Y_Kmeans = kmeans.fit_predict(Y)

# Visualizamos el grafico

plt.scatter(Y[Y_Kmeans == 0, 0], Y[Y_Kmeans == 0,1],s = 100, c='red', label = 'Cluster 1')

plt.scatter(Y[Y_Kmeans == 1, 0], Y[Y_Kmeans == 1,1],s = 100, c='blue', label = 'Cluster 2')

plt.scatter(Y[Y_Kmeans == 2, 0], Y[Y_Kmeans == 2,1],s = 100, c='green', label = 'Cluster 3')

plt.scatter(Y[Y_Kmeans == 3, 0], Y[Y_Kmeans == 3,1],s = 100, c='cyan', label = 'Cluster 4')

plt.scatter(Y[Y_Kmeans == 4, 0], Y[Y_Kmeans == 4,1],s = 100, c='magenta', label = 'Cluster 5')

plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], s = 300, c = 'yellow', label = 'Centroids')
    
plt.title('Clusters de clientes')
plt.xlabel('EDAD')
plt.ylabel('PORCENTAJE DE GASTO(1-100)')
plt.legend()
plt.show()

Y = dataset.iloc[:,[2,3]].values

from sklearn.cluster import KMeans

#Aplicamos KMeans para el dataset con un numero de 5 clusters

kmeans=KMeans(n_clusters= 5, init = 'k-means++', max_iter = 300, n_init = 10, random_state = 0)
Y_Kmeans = kmeans.fit_predict(Y)

# Visualizamos el grafico

plt.scatter(Y[Y_Kmeans == 0, 0], Y[Y_Kmeans == 0,1],s = 100, c='red', label = 'Cluster 1')

plt.scatter(Y[Y_Kmeans == 1, 0], Y[Y_Kmeans == 1,1],s = 100, c='blue', label = 'Cluster 2')

plt.scatter(Y[Y_Kmeans == 2, 0], Y[Y_Kmeans == 2,1],s = 100, c='green', label = 'Cluster 3')

plt.scatter(Y[Y_Kmeans == 3, 0], Y[Y_Kmeans == 3,1],s = 100, c='cyan', label = 'Cluster 4')

plt.scatter(Y[Y_Kmeans == 4, 0], Y[Y_Kmeans == 4,1],s = 100, c='magenta', label = 'Cluster 5')

plt.scatter(kmeans.cluster_centers_[:,0], kmeans.cluster_centers_[:,1], s = 300, c = 'yellow', label = 'Centroids')
    
plt.title('Clusters de clientes')
plt.xlabel('EDAD')
plt.ylabel('INGRESO ANUAL (k$)')
plt.legend()
plt.show()